function [shapes,vol] = makeSkinWithMask(vol,layers)
%makeSkin7 此处显示有关此函数的摘要
%   此处显示详细说明
[gridX, gridY, ~] = size(vol);
gridZ = sum(layers);
vol = zeros([gridX, gridY, gridZ], 'uint8');
layersZ = cumsum(layers)';
shapes = ['{"Shapes":['...
    '{"Grid": {"Tag":0, "Size":[' num2str(gridX) ',' num2str(gridY) ',' num2str(gridZ) ']}},'...
    '{"Box": {"Tag":1, "O": [0,0,0], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(1)) ']}},' ...
    '{"Box": {"Tag":2, "O": [0,0, ' num2str(layersZ(1)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(2)) ']}},' ...
    '{"Box": {"Tag":3, "O": [0,0, ' num2str(layersZ(2)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(3)) ']}},' ...
    '{"Box": {"Tag":4, "O": [0,0, ' num2str(layersZ(3)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(4)) ']}},' ...
    '{"Box": {"Tag":5, "O": [0,0, ' num2str(layersZ(4)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(5)) ']}},' ...
    '{"Box": {"Tag":6, "O": [0,0, ' num2str(layersZ(5)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(6)) ']}},' ...
    '{"Box": {"Tag":7, "O": [0,0, ' num2str(layersZ(6)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(7)) ']}},' ...
    '{"Box": {"Tag":8, "O": [0,0, ' num2str(layersZ(7)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(8)) ']}},' ...
    '{"Box": {"Tag":9, "O": [0,0, ' num2str(layersZ(8)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(9)) ']}},' ...
    '{"Box": {"Tag":10, "O": [0,0, ' num2str(layersZ(9)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(10)) ']}},' ...
    '{"Box": {"Tag":11, "O": [0,0, ' num2str(layersZ(10)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(11)) ']}},' ...
    '{"Box": {"Tag":12, "O": [0,0, ' num2str(layersZ(11)) '], "Size": [' num2str(gridX) ',' num2str(gridY) ', ' num2str(layers(12)) ']}},' ...
    '{"Cylinder": {"Tag":13, "C0": [' num2str(gridX/2) ',' num2str(gridY/2) ',40], "C1": [' num2str(gridX/2) ',' num2str(gridY/2) ',60], "R": 350}},' ...
    '{"Cylinder": {"Tag":14, "C0": [' num2str(gridX/2) ',' num2str(gridY/2) ',40], "C1": [' num2str(gridX/2) ',' num2str(gridY/2) ',60], "R": 110}}' ...
    ']}'];
end